'use client';

import React, { useState, useEffect } from 'react';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { Select } from '@/components/ui/Select';
import type { TransactionFormData, PaymentMethod } from '@/types';
import { MasterService } from '@/lib/masters-client';
import { formatDateForInput, validateAmount } from '@/lib/utils';

interface TransactionFormProps {
  initialData?: Partial<TransactionFormData> & { isAutoGenerated?: boolean };
  onSubmit: (data: TransactionFormData) => Promise<void>;
  onCancel?: () => void;
  loading?: boolean;
}

export const TransactionForm: React.FC<TransactionFormProps> = ({
  initialData,
  onSubmit,
  onCancel,
  loading = false,
}) => {
  const [formData, setFormData] = useState<TransactionFormData>({
    date: initialData?.date || formatDateForInput(new Date()),
    paymentMethodId: initialData?.paymentMethodId || '',
    store: initialData?.store || '',
    purpose: initialData?.purpose || '',
    type: initialData?.type || 'expense',
    amount: initialData?.amount || 0,
  });

  const [paymentMethods, setPaymentMethods] = useState<PaymentMethod[]>([]);
  const [errors, setErrors] = useState<Partial<Record<keyof TransactionFormData, string>>>({});
  
  // 引き落とし取引かどうかを判定
  const isWithdrawalTransaction = initialData?.isAutoGenerated || false;

  useEffect(() => {
    loadPaymentMethods();
  }, []);

  const loadPaymentMethods = async () => {
    const result = await MasterService.getPaymentMethods();
    if (result.success && result.data) {
      setPaymentMethods(result.data);
    }
  };

  const validateForm = (): boolean => {
    const newErrors: Partial<Record<keyof TransactionFormData, string>> = {};

    if (!formData.date) {
      newErrors.date = '日付を入力してください';
    }

    // 引き落とし取引の場合は日付のみバリデーション
    if (!isWithdrawalTransaction) {
      if (!formData.paymentMethodId) {
        newErrors.paymentMethodId = '支払い方法を選択してください';
      }

      if (!validateAmount(formData.amount) || formData.amount <= 0) {
        newErrors.amount = '正しい金額を入力してください';
      }
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!validateForm()) {
      return;
    }

    try {
      await onSubmit(formData);
    } catch (error) {
      console.error('Form submission error:', error);
    }
  };

  const handleInputChange = (field: keyof TransactionFormData, value: string | number) => {
    setFormData(prev => ({
      ...prev,
      [field]: value,
    }));

    if (errors[field]) {
      setErrors(prev => ({
        ...prev,
        [field]: undefined,
      }));
    }
  };

  const paymentMethodOptions = paymentMethods.map(method => ({
    value: method.id,
    label: method.name,
  }));

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      {isWithdrawalTransaction && (
        <div className="mb-4 p-3 bg-blue-50 border border-blue-200 rounded-lg">
          <p className="text-sm text-blue-700">
            <span className="font-medium">引き落とし取引</span>
            - 日付のみ編集可能です。金額や支払い方法は自動計算されます。
          </p>
        </div>
      )}
      
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <Input
          label="日付"
          type="date"
          value={formData.date}
          onChange={(e) => handleInputChange('date', e.target.value)}
          error={errors.date}
          required
        />

        <Select
          label="支払い方法"
          options={paymentMethodOptions}
          value={formData.paymentMethodId}
          onChange={(e) => handleInputChange('paymentMethodId', e.target.value)}
          placeholder="支払い方法を選択"
          error={errors.paymentMethodId}
          required
          disabled={isWithdrawalTransaction}
        />
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <Input
          label="使用店舗"
          type="text"
          value={formData.store}
          onChange={(e) => handleInputChange('store', e.target.value)}
          placeholder="店舗名を入力（任意）"
          disabled={isWithdrawalTransaction}
        />

        <Input
          label="用途"
          type="text"
          value={formData.purpose}
          onChange={(e) => handleInputChange('purpose', e.target.value)}
          placeholder="用途を入力（任意）"
          disabled={isWithdrawalTransaction}
        />
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <Select
          label="種別"
          options={[
            { value: 'income', label: '収入' },
            { value: 'expense', label: '支出' },
          ]}
          value={formData.type}
          onChange={(e) => handleInputChange('type', e.target.value as 'income' | 'expense')}
          required
          disabled={isWithdrawalTransaction}
        />

        <Input
          label="金額"
          type="text"
          inputMode="decimal"
          pattern="[0-9]*\.?[0-9]*"
          value={formData.amount.toString()}
          onChange={(e) => handleInputChange('amount', Number(e.target.value) || 0)}
          error={errors.amount}
          placeholder="金額を入力"
          required
          disabled={isWithdrawalTransaction}
        />
      </div>

      <div className="flex space-x-3 pt-4">
        <Button
          type="submit"
          loading={loading}
          className="flex-1"
        >
          {initialData ? '更新' : '登録'}
        </Button>
        
        {onCancel && (
          <Button
            type="button"
            variant="secondary"
            onClick={onCancel}
            className="flex-1"
          >
            キャンセル
          </Button>
        )}
      </div>
    </form>
  );
};